-- =====================================================
-- 1. ユーザー (users)
-- =====================================================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- =====================================================
-- 2. キャラクターマスタ (characters)
-- =====================================================
CREATE TABLE characters (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    image_path VARCHAR(255),
    attribute VARCHAR(50)
);

-- =====================================================
-- 3. 診断質問マスタ (questions)
-- =====================================================
CREATE TABLE questions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_questions_sort UNIQUE (sort_order)
);

-- =====================================================
-- 4. 選択肢マスタ (choices)
-- =====================================================
CREATE TABLE choices (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INT NOT NULL,
    body VARCHAR(255) NOT NULL,
    CONSTRAINT fk_choices_question FOREIGN KEY (question_id) REFERENCES questions (id)
);

-- =====================================================
-- 5. 選択肢キャラクタースコア (choice_character_scores)
-- =====================================================
CREATE TABLE choice_character_scores (
    choice_id INT NOT NULL,
    character_id INT NOT NULL,
    score INT NOT NULL DEFAULT 1,
    PRIMARY KEY (choice_id, character_id),
    CONSTRAINT fk_scores_choice FOREIGN KEY (choice_id) REFERENCES choices (id),
    CONSTRAINT fk_scores_character FOREIGN KEY (character_id) REFERENCES characters (id)
);

-- =====================================================
-- 6. 診断結果履歴 (diagnosis_results)
-- =====================================================
CREATE TABLE diagnosis_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    character_id INT NOT NULL,
    diagnosed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_results_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_results_character FOREIGN KEY (character_id) REFERENCES characters (id)
);